{% set version = "2.1.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mvoutlier
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/mvoutlier_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mvoutlier/mvoutlier_{{ version }}.tar.gz
  sha256: 3a2b48bc6f07c5bf77d35555c0934c21d9b7ee171f5c60e0589a6d8dbcfe86d2

build:
  noarch: generic
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-robcompositions
    - r-robustbase
    - r-sgeostat
  run:
    - r-base
    - r-robcompositions
    - r-robustbase
    - r-sgeostat

test:
  commands:
    - $R -e "library('mvoutlier')"  # [not win]
    - "\"%R%\" -e \"library('mvoutlier')\""  # [win]

about:
  home: http://cstat.tuwien.ac.at/filz
  license: GPL-3.0-or-later
  summary: Various Methods for Multivariate Outlier Detection.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
