travis:
  secure:
    BINSTAR_TOKEN: UkEudjYAtAyu3VxGHNchqBGOKVH5GPzAAZQ9aqAJNBykLBOU3emyFLhNuAGDmGV2WXefuK9en8ogWGWiY4JAATfj7sBY2E2NFErEmn4tOQ7HKOrrCSrT6SA8H9T9fQ0B98977EA4OYLYyodEOqIrWfZd6Qc56gcsbK6TKHrofX5d3oIHg/3c+yK2SM/P0rIqNwHMC4r4WaM0Y9WuC1IAEtqny2+etqdM8Khh5iXnqEWk7JI90eAshOEJL5CWCYEJ5JGp4Ap9ELsB1E2lv2evSFAKI9uF85uGdSQcCB87uT+4sQ1XBHsonqsw54ki5AS78eteVuv06XG20vDh/TUwfqmC68uFgf7pRmjlENzVyd999tk8wTWTLH2GGhFyTVenWcwP8DHvSzj5YJyQQjWIRHBdISs1mFMS1f93syCWnkRy5Vb7lnW9bQsesM4RQf9pZV3rZoAnkVXUjC2NFZmW7maNYZPqfGaFdvjp1Nn4CSdp9TdE3nNqvFh0trNm9KRiqsOV/KRlqDjsp2pWQss2bEx140xTuFgxMIhZP+qwMMW4mO3FtSBhbx4gJzCaWWz85nJzb6nuBJEkE6a5Tj6lqB0f0HJakDXzfJVqSfvjKwxUAUnorSnkrBnjGiYfufC2fE+owmI3Xftokpy1cx9m+tYCdolF9Q6qOyrLuhYvkbA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
