travis:
  secure:
    BINSTAR_TOKEN: ovulUnLVZrYnC+YdE3g84HyWYtOlWKcin28IkFaBhxGD0E46Phh9tjN/5D7GpAT8RgzECjEOQ3NUnaBNM25YW+6uRLv4Q1rRCIb4vd8czJdoqI+DZDNcX457jUrcmO/lOj2g8Q9gzRXYJiCtMYFLcuVUHtTe7L2ediBPnQ886ltsXwmDP5sPHPgJujwS9xDXMnRNu+wlnistrwHM1EoacIXrpzRMkAPWk4uLRVbt/QopYZQme9s1KYj/4D+jyfhOrK9auOD6hxeVivpqDYeQyhKmcqXXQtHF3AVkSjA77LaWLCGlhD35MZBqIPS7AMyrBEKTR45nFpvMFGk8WDZmb51BWpgTOjyiSrYcPT7KRYWTZ0o6sTToWGSn8YEV1we1ecn18NZxLQRCs1gF9A/1Ku4vJO8xw2EY51OzspfuCYC0byvjR1cps2PjYJjAOGt9xl2oXt5fzE36CRUmq0+WzFM7VEbRTepYXNxZiNjP94Y0OCApbmSz4LDI701JocoiHpHL/WYU+s4//41YBdpOAydNXpWclkMP1PJ4JITdAzPSInHMmtJAtB8VXScHl4biQ1Q8mZdazmwpXbjM3TmW4kNNMUhBck4M6aScONUJERpekXuemHqj+dLz91DzVBJ31jigDoQ0HeH3ZNiMVUZDwcyq1kA388cxkFyjKmyh3Ao=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
